version: "2.1"

services:
  docker-db:
    image: postgres
    environment:
      - DATABASE_HOST=docker-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inventory_database
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  seed:
    build: Database/
    depends_on:
      docker-db:
        condition: service_healthy
    environment:
      - NODE_ENV=development

  api:
    build: Server/
    ports:
      - 8080:8080
    depends_on:
      - docker-db
      - seed
    volumes:
      - ${PWD}/Server:/app

  ui:
    build: FrontEnd/project-app
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ${PWD}/FrontEnd/project-app:/app
      - /app/node_modules
